/*
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;

use super::{Error, configuration};

pub struct ApiTokenAuthApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ApiTokenAuthApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> ApiTokenAuthApiClient {
        ApiTokenAuthApiClient {
            configuration,
        }
    }
}

pub trait ApiTokenAuthApi {
    fn api_token_auth_create(&self, ) -> Result<(), Error>;
}

impl ApiTokenAuthApi for ApiTokenAuthApiClient {
    fn api_token_auth_create(&self, ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/api_token_auth/", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

}
