/*
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct JobsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl JobsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> JobsApiClient {
        JobsApiClient { configuration }
    }
}

pub trait JobsApi {
    fn jobs_create(
        &self,
        data: crate::models::Job,
        authorization: &str,
    ) -> Result<crate::models::Job, Error>;
    fn jobs_list(&self, page: i32) -> Result<crate::models::InlineResponse2001, Error>;
    fn jobs_update(
        &self,
        jobslurmid: &str,
        data: crate::models::Job,
        authorization: &str,
    ) -> Result<crate::models::Job, Error>;
}

impl JobsApi for JobsApiClient {
    fn jobs_create(
        &self,
        data: crate::models::Job,
        authorization: &str,
    ) -> Result<crate::models::Job, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/jobs/", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.header("Authorization", authorization.to_string());
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&data);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn jobs_list(&self, page: i32) -> Result<crate::models::InlineResponse2001, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/jobs/", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn jobs_update(
        &self,
        jobslurmid: &str,
        data: crate::models::Job,
        authorization: &str,
    ) -> Result<crate::models::Job, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/jobs/{jobslurmid}/",
            configuration.base_path,
            jobslurmid = crate::apis::urlencode(jobslurmid)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.header("Authorization", authorization.to_string());
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&data);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
