/* 
 * Snippets API
 *
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct UseraccountassociationsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> UseraccountassociationsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> UseraccountassociationsApiClient<C> {
        UseraccountassociationsApiClient {
            configuration: configuration,
        }
    }
}

pub trait UseraccountassociationsApi {
    fn useraccountassociations_list(&self, page: i32) -> Box<Future<Item = ::models::InlineResponse2002, Error = Error>>;
    fn useraccountassociations_partial_update(&self, id: i32, data: ::models::UserAccount) -> Box<Future<Item = ::models::UserAccount, Error = Error>>;
    fn useraccountassociations_read(&self, id: i32) -> Box<Future<Item = ::models::UserAccount, Error = Error>>;
    fn useraccountassociations_update(&self, id: i32, data: ::models::UserAccount) -> Box<Future<Item = ::models::UserAccount, Error = Error>>;
}


impl<C: hyper::client::Connect>UseraccountassociationsApi for UseraccountassociationsApiClient<C> {
    fn useraccountassociations_list(&self, page: i32) -> Box<Future<Item = ::models::InlineResponse2002, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("page", &page.to_string())
            .finish();
        let uri_str = format!("{}/useraccountassociations/{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::InlineResponse2002, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn useraccountassociations_partial_update(&self, id: i32, data: ::models::UserAccount) -> Box<Future<Item = ::models::UserAccount, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Patch;

        let uri_str = format!("{}/useraccountassociations/{id}/", configuration.base_path, id=id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());


        let serialized = serde_json::to_string(&body).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::UserAccount, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn useraccountassociations_read(&self, id: i32) -> Box<Future<Item = ::models::UserAccount, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let uri_str = format!("{}/useraccountassociations/{id}/", configuration.base_path, id=id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::UserAccount, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn useraccountassociations_update(&self, id: i32, data: ::models::UserAccount) -> Box<Future<Item = ::models::UserAccount, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Put;

        let uri_str = format!("{}/useraccountassociations/{id}/", configuration.base_path, id=id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());


        let serialized = serde_json::to_string(&body).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::UserAccount, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
