/*
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<String>,
    #[serde(rename = "results")]
    pub results: Vec<crate::models::Partition>,
}

impl InlineResponse2002 {
    pub fn new(count: i32, results: Vec<crate::models::Partition>) -> InlineResponse2002 {
        InlineResponse2002 {
            count,
            next: None,
            previous: None,
            results,
        }
    }
}
