/*
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    #[serde(rename = "name")]
    pub name: String,
}

impl Node {
    pub fn new(name: String) -> Node {
        Node {
            name,
        }
    }
}


