/* 
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ScgUser {
  #[serde(rename = "username")]
  username: Option<String>,
  /// Required. Must be an existing email address.
  #[serde(rename = "email")]
  email: String
}

impl ScgUser {
  pub fn new(email: String) -> ScgUser {
    ScgUser {
      username: None,
      email: email
    }
  }

  pub fn set_username(&mut self, username: String) {
    self.username = Some(username);
  }

  pub fn with_username(mut self, username: String) -> ScgUser {
    self.username = Some(username);
    self
  }

  pub fn username(&self) -> Option<&String> {
    self.username.as_ref()
  }

  pub fn reset_username(&mut self) {
    self.username = None;
  }

  pub fn set_email(&mut self, email: String) {
    self.email = email;
  }

  pub fn with_email(mut self, email: String) -> ScgUser {
    self.email = email;
    self
  }

  pub fn email(&self) -> &String {
    &self.email
  }


}



