/*
 * myBRC REST API
 *
 * REST API for myBRC
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ScgUser {
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Required. Must be an existing email address.
    #[serde(rename = "email")]
    pub email: String,
}

impl ScgUser {
    pub fn new(email: String) -> ScgUser {
        ScgUser {
            username: None,
            email,
        }
    }
}


